### ISSUE TITLE
issues after new update

### ISSUE THREAD

**Issue by r6spy** [devilismyfriend/StableTuner#109]
runned in to few issues with the new update
first one:
after you run the instalation and all pip install xformers==0.0.17.dev442 don't install
they give error:
ERROR: Could not find a version that satisfies the requirement xformers==0.0.17.dev442 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17.dev447, 0.0.17.dev448, 0.0.17.dev449, 0.0.17.dev451, 0.0.17.dev461, 0.0.17.dev464)
ERROR: No matching distribution found for xformers==0.0.17.dev442

fine, i've installed different package of xformers to see what happens but never mind.
next issue is when you run the stabletuner.cmd file
you get 
Traceback (most recent call last):
  File "E:\st\stabletuner\scripts\configuration_gui.py", line 13, in <module>
    import converters
  File "E:\st\stabletuner\scripts\converters.py", line 26, in <module>
    from diffusers import (
ModuleNotFoundError: No module named 'diffusers'

**Comment by devilismyfriend** [comment]
pull latest and run the installer again
