### ISSUE TITLE
Bug: When selecting 'fp32' for precision, invalid value for --mixed-precision is passed to command line

### ISSUE THREAD

**Issue by revision4** [devilismyfriend/StableTuner#12]
When selecting 'fp32' for precision, should pass '--mixed-precision=no' instead of '--mixed-precision=fp32'

trainer.py: error: argument --mixed_precision: invalid choice: 'fp32' (choose from 'no', 'fp16', 'bf16')
Traceback (most recent call last):
  File "C:\Users\revis\.conda\envs\ST\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\revis\.conda\envs\ST\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\revis\.conda\envs\ST\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\revis\.conda\envs\ST\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\revis\.conda\envs\ST\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\revis\.conda\envs\ST\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by devilismyfriend** [comment]
Should be fixed now
