### ISSUE TITLE
CUDNN, BadZipFile: file is not a zip file

### ISSUE THREAD

**Issue by TeKett** [devilismyfriend/StableTuner#133]
Trying to install on win10, it says the "cudnn_windows.zip" file is not a zip file. It gives me the option to press any key and then closes. When i try to run the StableTuner.cmd (Which i assume is the executable?) it just runs some commands that is too fast to read and then closes.

**Comment by wyxos** [comment]
Experiencing a similar issue

```
Traceback (most recent call last):
  File "D:\StableTuner\scripts\windows_install.py", line 161, in <module>
    with zipfile.ZipFile('cudnn_windows.zip','r') as zip_ref:
  File "C:\Users\username\anaconda3\envs\ST\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "C:\Users\username\anaconda3\envs\ST\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by wyxos** [comment]
Happens right after it logs "Downloading CUDNN 8.6"
