### ISSUE TITLE
No module named model_util

### ISSUE THREAD

**Issue by JPW0080** [devilismyfriend/StableTuner#17]
Gave the most recent version a try and after downloading/extracting/overwriting the result was the below:

conda activate diffusers
cd C:\StableTuner

(diffusers) C:\StableTuner>python configuration_gui.py
Traceback (most recent call last):
  File "C:\StableTuner\configuration_gui.py", line 13, in <module>
    from scripts import converters
  File "C:\StableTuner\scripts\converters.py", line 44, in <module>
    import model_util
ModuleNotFoundError: No module named 'model_util'

The remedy was editing line 44 of 
C:\StableTuner\scripts\converters.py

from scripts import model_util

The UI was was able to launch after that.

Also, unless intentional, Small typo, on UI, it reads StableTune
Another issue, disregard if already known.

It seems that if there is no Internet connection, ckpt models can not be converted to diffusers?
.yamls are still trying to be fetched even if the .yaml is already alongside the model.

**Comment by JPW0080** [comment]
It appears my issue was using the wrong configuration_gui.py
Rather than creating an entire new environment, I've just been installing any new required dependencies in a previous DB env.

Dragging/Dropping/Replacing new code

conda activate diffusers
cd C:\StableTuner
python configuration_gui.py

Completely skipping running configuration_gui.py from the scripts folder...
With the new GUI, it's back to no right-click menu? or perhaps it's time to give ST it's own environment.

For the offline issue, it's possible to use the sd_dreambooth extension offline. 
SymLink the working model folder contents for use in ST.
