### ISSUE TITLE
Latest pull - issue

### ISSUE THREAD

**Issue by MV799** [devilismyfriend/StableTuner#44]
Receiving weird error in the latest pull
Traceback (most recent call last):
  File "D:\StableTuner\scripts\trainer.py", line 16, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'
Traceback (most recent call last):
  File "C:\Users\Desktop\Documents\Anaconda\envs\ST\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Desktop\Documents\Anaconda\envs\ST\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Desktop\Documents\Anaconda\envs\ST\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Desktop\Documents\Anaconda\envs\ST\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Desktop\Documents\Anaconda\envs\ST\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Desktop\Documents\Anaconda\envs\ST\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by MV799** [comment]
found it:
pip install keyboard
