### ISSUE TITLE
CKPT to Diffusers error

### ISSUE THREAD

**Issue by MV799** [devilismyfriend/StableTuner#49]
Trying to convert ckpt that work well in AUTO1111, but fails in ST

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Desktop\Documents\Anaconda\envs\ST\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Desktop\Documents\Anaconda\envs\ST\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 531, in _clicked
    self._command()
  File "D:\StableTuner\scripts\configuration_gui.py", line 1859, in <lambda>
    self.convert_ckpt_to_diffusers_button = ctk.CTkButton(self.toolbox_frame_subframe, text="Convert CKPT To Diffusers", command=lambda:self.convert_ckpt_to_diffusers())
  File "D:\StableTuner\scripts\configuration_gui.py", line 2212, in convert_ckpt_to_diffusers
    version, prediction = self.get_sd_version(ckpt_path)
  File "D:\StableTuner\scripts\configuration_gui.py", line 2527, in get_sd_version
    checkpoint = checkpoint["state_dict"]
KeyError: 'state_dict'

**Comment by MV799** [comment]
I tried to convert the same in dreambooth extension and it worked well, so CKPT is fine, definitelly something in ST

**Comment by devilismyfriend** [comment]
Some models, especially ones that were merged with others can have custom
structures which will fail to convert in ST

**Comment by devilismyfriend** [comment]
this has been fixed
