### ISSUE TITLE
RuntimeError thrown while loading CKPT

### ISSUE THREAD

**Issue by Alaith** [devilismyfriend/StableTuner#67]
Hello, I encountered the following RuntimeError while loading the [WD 1.4](https://huggingface.co/hakurei/waifu-diffusion-v1-4) model from CKPT on disk: 
```
(base) PS C:\Users\alaith\git\github.com\devilismyfriend\StableTuner> .\StableTuner.cmd
Environment name is set as "ST" as per environment.yaml
anaconda3/miniconda3 detected in C:\Users\alaith\anaconda3
Starting conda environment "ST" from C:\Users\alaith\anaconda3
loading model from: C:/Users/alaith/git/github.com/AUTOMATIC1111/stable-diffusion-webui/models/Stable-diffusion/wd-1-4-anime_e1.ckpt
loading u-net: <All keys matched successfully>
loadint vae: <All keys matched successfully>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\alaith\anaconda3\envs\ST\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\alaith\anaconda3\envs\ST\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 531, in _clicked
    self._command()
  File "C:\Users\alaith\git\github.com\devilismyfriend\StableTuner\scripts\configuration_gui.py", line 2673, in choose_model
    convert = converters.Convert_SD_to_Diffusers(sd_file,model_path,prediction_type=prediction,version=version)
  File "C:\Users\alaith\git\github.com\devilismyfriend\StableTuner\scripts\converters.py", line 61, in __init__
    self.main()
  File "C:\Users\alaith\git\github.com\devilismyfriend\StableTuner\scripts\converters.py", line 89, in main
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(v2_model, self.checkpoint_path)
  File "C:\Users\alaith\git\github.com\devilismyfriend\StableTuner\scripts\model_util.py", line 1205, in load_models_from_stable_diffusion_checkpoint
    info = text_model.load_state_dict(converted_text_encoder_checkpoint)
  File "C:\Users\alaith\anaconda3\envs\ST\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Unexpected key(s) in state_dict: "text_model.encoder.text_model.embeddings.position_ids".
```
I noticed someone else seemed to have a similar error a few days ago, but as that one was fixed I thought I should open another issue.

Running on Windows 10 at commit `94d2dd28ac1b70d91e76a521e06633b2ebced508` (head of main branch as of this issue being created).

**Comment by MV799** [comment]
I have this as well. Used to work fine.
